"""The desert's pack — the flats: a spring in the low ground, the saguaro's slow years, the prickly-pear's brief fruit, the sagebrush under its nurse plants; jackrabbits, tortoises, shrikes, kit-foxes, migrating sandgrouse, peccaries; bighorn and mountain lion passing. Same engine; water means more here."""


SPEC = {'plants': {'saguaro': {'desc': 'saguaro',
                        'kind': 'tree',
                        'shape': 'cactus',
                        'mature_age': 14,
                        'old_age': 260,
                        'max_age': 340,
                        'seed_season': (0, 1, 2),
                        'seed_prob': 0.05,
                        'seed_radius': 3,
                        'light_need': 0.5,
                        'shade_self': 0.22,
                        'shade_adjacent': 0.1,
                        'storm_fall_mature': 0.01,
                        'storm_fall_old': 0.02,
                        'frost_hp': 0.1,
                        'emoji': '🌵'},
            'palo-verde': {'desc': 'palo-verde',
                           'kind': 'tree',
                           'shape': 'deciduous',
                           'mature_age': 6,
                           'old_age': 100,
                           'max_age': 150,
                           'seed_season': (0, 1, 2),
                           'seed_prob': 0.22,
                           'seed_radius': 4,
                           'light_need': 0.62,
                           'shade_self': 0.28,
                           'shade_adjacent': 0.14,
                           'storm_fall_mature': 0.02,
                           'storm_fall_old': 0.04,
                           'frost_hp': 0.15,
                           'emoji': '🌳'},
            'cottonwood': {'desc': 'cottonwood',
                           'kind': 'tree',
                           'shape': 'deciduous',
                           'mature_age': 8,
                           'old_age': 140,
                           'max_age': 200,
                           'seed_season': (0, 1, 2),
                           'seed_prob': 0.14,
                           'seed_radius': 2,
                           'light_need': 0.45,
                           'shade_self': 0.4,
                           'shade_adjacent': 0.15,
                           'storm_fall_mature': 0.02,
                           'storm_fall_old': 0.05,
                           'frost_hp': 0.12,
                           'near_water': 3,
                           'emoji': '🌳'},
            'prickly-pear': {'desc': 'prickly-pear',
                             'kind': 'shrub',
                             'shape': 'bush',
                             'mature_age': 5,
                             'old_age': 50,
                             'max_age': 70,
                             'seed_season': (0, 2),
                             'seed_prob': 0.1,
                             'seed_radius': 1,
                             'light_need': 0.6,
                             'blight_sensitivity': 0.8,
                             'fruit_season': 1,
                             'fruit_week': 1,
                             'fruit_prob': 0.8,
                             'sucker_prob': 0.03,
                             'emoji': '🫑'},
            'sagebrush': {'desc': 'sagebrush',
                          'kind': 'understory',
                          'shape': 'fronds',
                          'mature_age': 3,
                          'old_age': 40,
                          'max_age': 60,
                          'seed_season': (1, 2),
                          'seed_prob': 0.05,
                          'seed_radius': 1,
                          'light_need': 0.42,
                          'spread_prob': 0.08,
                          'spread_times': 2,
                          'spread_radius': 1,
                          'scorch_light': 0.85,
                          'scorch_hp': 0.6,
                          'blight_sensitivity': 1.6,
                          'emoji': '🌾'}},
 'animals': {'jackrabbit': {'hunger_drain': 0.8,
                            'lifespan': 55,
                            'speed': 3,
                            'scan': 4,
                            'lit_size': 3,
                            'lit_prob': 0.26,
                            'breed_seasons': (0, 1),
                            'energy_breed': 6.0,
                            'diet': 'graze',
                            'flee_from': ('kit-fox', 'lion'),
                            'flee_range': 3,
                            'flee_cells': 4,
                            'graze_at': 0.12,
                            'graze_take': 0.2,
                            'seek_at': 0.16,
                            'cap': 24,
                            'winterslow': 0.5},
             'tortoise': {'hunger_drain': 0.25,
                          'lifespan': 380,
                          'speed': 1,
                          'scan': 2,
                          'lit_size': 1,
                          'lit_prob': 0.05,
                          'breed_seasons': (0,),
                          'energy_breed': 7.0,
                          'diet': 'glean',
                          'graze_at': 0.25,
                          'graze_take': 0.05,
                          'cap': 6,
                          'winterslow': 0.1},
             'kit-fox': {'hunt': 'jackrabbit',
                         'hunt_prob': 0.5,
                         'hunting_density_scale': 10.0,
                         'hunt_prob_min': 0.3,
                         'hunger_drain': 0.7,
                         'lifespan': 100,
                         'speed': 3,
                         'scan': 6,
                         'lit_size': 2,
                         'lit_prob': 0.1,
                         'breed_seasons': (0, 2),
                         'energy_breed': 7.0,
                         'cap': 5,
                         'winterslow': 0.6},
             'shrike': {'strike': ('jackrabbit',),
                        'strike_prob': 0.15,
                        'strike_range': 5,
                        'hunger_drain': 0.45,
                        'lifespan': 90,
                        'speed': 2,
                        'scan': 3,
                        'lit_size': 1,
                        'lit_prob': 0.1,
                        'breed_seasons': (0, 1),
                        'energy_breed': 6.0,
                        'cap': 3,
                        'winterslow': 0.8,
                        'flyer': True},
             'sandgrouse': {'hunger_drain': 0.5,
                            'lifespan': 40,
                            'speed': 4,
                            'scan': 3,
                            'lit_size': 3,
                            'lit_prob': 0.28,
                            'breed_seasons': (0, 1),
                            'energy_breed': 5.0,
                            'diet': 'glean',
                            'graze_at': 0.2,
                            'graze_take': 0.04,
                            'migration': {'leave_at': 3, 'return_at': 0},
                            'cap': 12,
                            'winterslow': 0.8,
                            'flyer': True},
             'peccary': {'hunger_drain': 0.5,
                         'lifespan': 130,
                         'speed': 1,
                         'scan': 3,
                         'lit_size': 2,
                         'lit_prob': 0.14,
                         'breed_seasons': (1, 2),
                         'energy_breed': 6.0,
                         'diet': 'scavenge',
                         'graze_at': 0.2,
                         'graze_take': 0.18,
                         'cap': 5,
                         'winterslow': 0.7},
             'bighorn': {'hunger_drain': 0.55,
                         'lifespan': 180,
                         'speed': 2,
                         'scan': 5,
                         'winterslow': 0.6,
                         'visitor': True},
             'lion': {'hunt': 'jackrabbit',
                      'hunt_prob': 0.55,
                      'hunting_density_scale': 12.0,
                      'hunt_prob_min': 0.35,
                      'prey2': 'bighorn',
                      'prey2_prob': 0.3,
                      'hunger_drain': 0.7,
                      'lifespan': 160,
                      'speed': 3,
                      'scan': 7,
                      'winterslow': 1.0,
                      'visitor': True}},
 'gen': {'noise_octaves': 3,
         'coarse_grid': 6,
         'tree_pool': {'saguaro': 2, 'palo-verde': 2},
         'shore_species': 'cottonwood',
         'shrub_species': 'prickly-pear',
         'understory_species': 'sagebrush',
         'elev_sigma': 0.35,
         'fert_sigma': 0.4,
         'wet_sigma': 0.3,
         'fert_base': 0.22,
         'fert_spread': 0.7,
         'moist_base': 0.18,
         'moist_spread': 0.7,
         'water_quantile': 0.06,
         'rock_quantile': 0.86,
         'near_water_moisture': 0.5,
         'p_tree_base': 0.55,
         'p_tree_slope': 0.5,
         'p_tree_moisture_min': 0.3,
         'p_tree_fert_min': 0.3,
         'willow_near_water_prob': 0.45,
         'initial_age_spread': (2, 60),
         'p_berry': 0.05,
         'grass_base': 0.22,
         'grass_fert': 0.3,
         'p_fern_shade': 0.5,
         'fern_scorch_light': 0.85,
         'starting_seedbank': {'saguaro': 6,
                               'palo-verde': 10,
                               'prickly-pear': 6,
                               'sagebrush': 10},
         'founder_names': 6,
         'founder_prob': 0.22,
         'starting_animals': {'jackrabbit': 22,
                              'tortoise': 6,
                              'kit-fox': 4,
                              'shrike': 3,
                              'sandgrouse': 12,
                              'peccary': 5}},
 'weather': {'rain_prob': {'0': 0.1, '1': 0.12, '2': 0.05, '3': 0.0},
             'natural_storm_prob': {'1': 0.01}},
 'cells': {'grass_regrow': {'0': 0.1, '1': 0.09, '2': 0.04, '3': 0.0}},
 'pop': {'base_residents': ['jackrabbit',
                            'tortoise',
                            'kit-fox',
                            'shrike',
                            'sandgrouse',
                            'peccary'],
         'water_seekers': ('jackrabbit', 'tortoise', 'kit-fox', 'lion', 'bighorn', 'peccary'),
         'visitor_species': ('bighorn', 'lion'),
         'flock_species': ('jackrabbit', 'sandgrouse'),
         'migration_default': 'sandgrouse',
         'visitor_default': 'bighorn',
         'bloom_species': 'prickly-pear'},
 'presentation': {'world_word': 'the flats',
                  'chronicler_role': 'a desert',
                  'chronicler_system': 'You are the Chronicler of a desert. One event: its '
                                       'data and a plain base sentence. Rewrite as ONE line '
                                       '(<=88 chars), same subject and place, new rhythm. '
                                       'Never another scene; never coordinates; do not echo '
                                       'listed recent lines. Only JSON: {"text":"..."}',
                  'soul_system': 'You are the World Soul of a small desert — the slow, '
                                 'fate-bearing presence behind its weathers and fortunes. '
                                 "Every few weeks you are given a digest of the flats' state "
                                 'and you choose ONE intervention, as a desert would be fated '
                                 'to receive: sometimes harsh, sometimes rare and generous, '
                                 'often nothing at all. Read the digest first: water is the '
                                 "desert's whole wealth; a drought after dry weeks is cruel "
                                 'twice.\n'
                                 'Valid fates: storm (a desert squall with wind-fall), drought '
                                 '(the dry weeks), blight (a creeping sickness in the green), '
                                 "bloom (the desert's brief flowering), migration (a species "
                                 'arrives at the edge), visitor (a lone bighorn or passing '
                                 'lion enters briefly), destiny (mark ONE creature whose life '
                                 'you will watch), quiet (the soul keeps its peace).\n'
                                 "For 'destiny' name a creature by the id number from the "
                                 "digest's 'known souls' list, and in 'destiny' write one "
                                 'short prophecy (under 70 characters) about its life — where '
                                 'it shall go, what it shall become. The engine keeps the '
                                 'watch and chronicles the fulfillment.\n'
                                 "Choose 'region' from NW, NE, SW, SE or all. 'strength' is 1 "
                                 "(mild) to 3 (severe). 'blight' may name one green thing: "
                                 'saguaro, palo-verde, cottonwood, prickly-pear, sagebrush. '
                                 "'migration' may name one creature: jackrabbit, tortoise, "
                                 "kit-fox, shrike, sandgrouse, peccary. 'visitor' names "
                                 'bighorn or lion.\n'
                                 "In 'intent' write one plain sentence (under 110 characters) "
                                 'saying what you intend, in the voice of the desert itself.\n'
                                 'Reply ONLY as JSON: {"action":"...", "region":"...", '
                                 '"strength":1, "species":null, "target":null, "destiny":null, '
                                 '"intent":"..."}',
                  'edge_name': 'the dunes',
                  'shore_place': "the spring's edge",
                  'season_lines': {0: 'Rain came to the flats; the desert greened.',
                                   1: "The monsoon's weeks settle over the flats.",
                                   2: 'Autumn, and the flats turn pale and dry.',
                                   3: 'Winter holds the flats; the nights bite.'},
                  'place_words': {'NW': 'the north-west flats',
                                  'NE': 'the north-east flats',
                                  'SW': 'the south-west flats',
                                  'SE': 'the south-east flats',
                                  'all': 'the flats'},
                  'creature_names': ['Duna',
                                     'Mescal',
                                     'Paloma',
                                     'Cirio',
                                     'Bosque',
                                     'Caliche',
                                     'Duende',
                                     'Espino',
                                     'Fiero',
                                     'Gavilan',
                                     'Hada',
                                     'Llanero',
                                     'Maguey',
                                     'Nube',
                                     'Ocotillo',
                                     'Pluma',
                                     'Roca',
                                     'Tierra',
                                     'Umbral',
                                     'Viento',
                                     'Yucca',
                                     'Brezo',
                                     'Cima',
                                     'Duelo',
                                     'Erial',
                                     'Filo',
                                     'Hormiga',
                                     'Isla',
                                     'Jardin',
                                     'Loma',
                                     'Madre',
                                     'Niebla',
                                     'Ojo',
                                     'Sombra',
                                     'Trueno',
                                     'Ceniza',
                                     'Alba',
                                     'Farol'],
                  'animal_emoji': {'jackrabbit': '🐇',
                                   'tortoise': '🐢',
                                   'kit-fox': '🦊',
                                   'shrike': '🐦',
                                   'sandgrouse': '🐧',
                                   'peccary': '🐖',
                                   'bighorn': '🐏',
                                   'lion': '🦁'},
                  'animal_body': {'jackrabbit': '#b09a7a',
                                  'tortoise': '#7d8a5a',
                                  'kit-fox': '#d4985a',
                                  'shrike': '#8f8f96',
                                  'sandgrouse': '#c8a86e',
                                  'peccary': '#6a564a',
                                  'bighorn': '#9a8878',
                                  'lion': '#c09a52'},
                  'shapes': {'saguaro': 'cactus',
                             'palo-verde': 'deciduous',
                             'cottonwood': 'deciduous',
                             'prickly-pear': 'bush',
                             'sagebrush': 'fronds',
                             'jackrabbit': 'rabbit',
                             'tortoise': 'tortoise',
                             'shrike': 'robin',
                             'sandgrouse': 'robin',
                             'peccary': 'boar',
                             'bighorn': 'stag',
                             'lion': 'wolf'},
                  'seasons_palette': {'spring': {'grass': '#7a9c4e',
                                                 'soil': '#8a6a3c',
                                                 'water': '#2a6474',
                                                 'rock': '#7a5c48',
                                                 'pine': '#4a7040',
                                                 'leaf': '#6f9f4a',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'under': '#688a4a',
                                                 'bush': '#5d8a45',
                                                 'fruit': '#c44a38',
                                                 'nightT': '#131822',
                                                 'nightB': '#201c18'},
                                      'summer': {'grass': '#9c9a58',
                                                 'soil': '#906a40',
                                                 'water': '#275a6b',
                                                 'rock': '#7d5f49',
                                                 'pine': '#46653c',
                                                 'leaf': '#83a050',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'under': '#7d8c50',
                                                 'bush': '#87804a',
                                                 'fruit': '#c07a58',
                                                 'nightT': '#0f131a',
                                                 'nightB': '#221a14'},
                                      'autumn': {'grass': '#b09a5c',
                                                 'soil': '#8a6238',
                                                 'water': '#275066',
                                                 'rock': '#6d5a4a',
                                                 'pine': '#405c40',
                                                 'leaf': '#a97c3c',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'under': '#8a7a4a',
                                                 'bush': '#906038',
                                                 'fruit': '#b0762f',
                                                 'nightT': '#14121a',
                                                 'nightB': '#241c12'},
                                      'winter': {'grass': '#9c9a88',
                                                 'soil': '#6d5c48',
                                                 'water': '#2a4a60',
                                                 'rock': '#6d6a70',
                                                 'pine': '#3a5240',
                                                 'leaf': '#7a7458',
                                                 'canopyDim': 0.9,
                                                 'wash': 'rgba(214,224,228,0.09)',
                                                 'under': '#6a7458',
                                                 'bush': '#6d684a',
                                                 'fruit': '#465148',
                                                 'nightT': '#0d1118',
                                                 'nightB': '#1e1f1e'}}},
 'gate': {'plants_min': 80}}
