"""The grove's own pack — the original forest: species tables, the planting recipe, the world's words, colours, emoji, names, shapes, and the soul's briefs. The engine still reads rules.R; the pack is where this nature lives."""


SPEC = {'plants': {'pine': {'kind': 'tree',
                     'mature_age': 20,
                     'old_age': 96,
                     'max_age': 240,
                     'seed_season': 2,
                     'seed_prob': 0.16,
                     'seed_radius': 3,
                     'light_need': 0.25,
                     'shade_self': 0.55,
                     'shade_adjacent': 0.3,
                     'storm_fall_mature': 0.05,
                     'storm_fall_old': 0.12,
                     'frost_hp': 0.0,
                     'emoji': 'pine',
                     'desc': 'pine'},
            'birch': {'kind': 'tree',
                      'mature_age': 12,
                      'old_age': 88,
                      'max_age': 160,
                      'seed_season': 2,
                      'seed_prob': 0.28,
                      'seed_radius': 6,
                      'light_need': 0.45,
                      'shade_self': 0.45,
                      'shade_adjacent': 0.22,
                      'storm_fall_mature': 0.09,
                      'storm_fall_old': 0.22,
                      'frost_hp': 0.15,
                      'emoji': 'leaf',
                      'desc': 'birch',
                      'blight_sensitivity': 1.6},
            'willow': {'kind': 'tree',
                       'mature_age': 9,
                       'old_age': 72,
                       'max_age': 140,
                       'seed_season': 2,
                       'seed_prob': 0.3,
                       'seed_radius': 3,
                       'near_water': 2,
                       'light_need': 0.4,
                       'shade_self': 0.4,
                       'shade_adjacent': 0.2,
                       'storm_fall_mature': 0.12,
                       'storm_fall_old': 0.3,
                       'frost_hp': 0.15,
                       'emoji': 'leaf',
                       'desc': 'willow'},
            'fern': {'kind': 'understory',
                     'mature_age': 2,
                     'old_age': 30,
                     'max_age': 58,
                     'light_need': 0.65,
                     'spread_prob': 0.16,
                     'spread_radius': 1,
                     'storm_fall_mature': 0.02,
                     'storm_fall_old': 0.05,
                     'frost_hp': 0.25,
                     'emoji': 'fern',
                     'desc': 'fern',
                     'blight_sensitivity': 1.6,
                     'scorch_light': 0.85,
                     'scorch_hp': 0.6,
                     'spread_times': 2},
            'berry': {'kind': 'shrub',
                      'mature_age': 3,
                      'old_age': 22,
                      'max_age': 40,
                      'seed_season': (0, 2),
                      'seed_prob': 0.22,
                      'seed_radius': 3,
                      'light_need': 0.5,
                      'shade_self': 0.03,
                      'shade_adjacent': 0.0,
                      'storm_fall_mature': 0.06,
                      'storm_fall_old': 0.15,
                      'frost_hp': 0.2,
                      'emoji': 'berry',
                      'desc': 'berry bush',
                      'fruit_season': 0,
                      'fruit_week': 1,
                      'fruit_prob': 0.8,
                      'sucker_prob': 0.045}},
 'animals': {'rabbit': {'hunger_drain': 0.8,
                        'lifespan': 60,
                        'speed': 3,
                        'scan': 4,
                        'lit_size': 3,
                        'lit_prob': 0.28,
                        'breed_seasons': (0, 1),
                        'energy_breed': 6.0,
                        'diet': 'graze',
                        'flee_from': ('fox', 'wolf'),
                        'flee_range': 3,
                        'flee_cells': 4,
                        'graze_at': 0.12,
                        'graze_take': 0.18,
                        'seek_at': 0.15,
                        'cap': 24,
                        'winterslow': 0.4,
                        'predators': ('fox', 'owl', 'wolf')},
             'deer': {'hunger_drain': 0.55,
                      'lifespan': 200,
                      'speed': 2,
                      'scan': 5,
                      'lit_size': 1,
                      'lit_prob': 0.1,
                      'breed_seasons': (0,),
                      'energy_breed': 8.0,
                      'diet': 'browse',
                      'browse_hunger': 6,
                      'browse_chance': 0.5,
                      'browse_hp': 1.5,
                      'graze_at': 0.15,
                      'graze_take': 0.12,
                      'seek_at': 0.15,
                      'cap': 10,
                      'winterslow': 0.5},
             'fox': {'hunt': 'rabbit',
                     'hunt_prob': 0.5,
                     'hunting_density_scale': 12.0,
                     'hunt_prob_min': 0.35,
                     'hunger_drain': 0.7,
                     'lifespan': 130,
                     'speed': 3,
                     'scan': 6,
                     'lit_size': 2,
                     'lit_prob': 0.09,
                     'breed_seasons': (0, 2),
                     'energy_breed': 7.0,
                     'cap': 6,
                     'winterslow': 0.6},
             'owl': {'strike': ('rabbit',),
                     'strike_prob': 0.18,
                     'strike_range': 5,
                     'hunger_drain': 0.5,
                     'lifespan': 160,
                     'speed': 2,
                     'scan': 2,
                     'lit_size': 1,
                     'lit_prob': 0.1,
                     'breed_seasons': (0, 1),
                     'energy_breed': 6.0,
                     'cap': 3,
                     'winterslow': 1.0},
             'robin': {'hunger_drain': 0.5,
                       'lifespan': 40,
                       'speed': 4,
                       'scan': 3,
                       'lit_size': 3,
                       'lit_prob': 0.3,
                       'breed_seasons': (0, 1),
                       'energy_breed': 5.0,
                       'diet': 'glean',
                       'graze_at': 0.2,
                       'graze_take': 0.04,
                       'migration': {'leave_at': 3, 'return_at': 0},
                       'cap': 14,
                       'winterslow': 0.75,
                       'flyer': True},
             'boar': {'hunger_drain': 0.5,
                      'lifespan': 140,
                      'speed': 1,
                      'scan': 3,
                      'lit_size': 2,
                      'lit_prob': 0.15,
                      'breed_seasons': (1, 2),
                      'energy_breed': 6.0,
                      'diet': 'scavenge',
                      'graze_at': 0.2,
                      'graze_take': 0.15,
                      'cap': 5,
                      'winterslow': 0.7},
             'stag': {'hunger_drain': 0.55,
                      'lifespan': 200,
                      'speed': 2,
                      'scan': 5,
                      'winterslow': 0.6,
                      'visitor': True},
             'wolf': {'hunt': 'rabbit',
                      'hunt_prob': 0.6,
                      'hunting_density_scale': 12.0,
                      'hunt_prob_min': 0.35,
                      'prey2': 'deer',
                      'prey2_prob': 0.3,
                      'hunger_drain': 0.7,
                      'lifespan': 180,
                      'speed': 3,
                      'scan': 7,
                      'winterslow': 1.0,
                      'visitor': True}},
 'gen': {'noise_octaves': 3,
         'coarse_grid': 6,
         'tree_pool': {'pine': 2, 'birch': 2},
         'shore_species': 'willow',
         'shrub_species': 'berry',
         'understory_species': 'fern',
         'elev_sigma': 0.35,
         'fert_sigma': 0.4,
         'wet_sigma': 0.3,
         'fert_base': 0.35,
         'fert_spread': 0.9,
         'moist_base': 0.25,
         'moist_spread': 0.6,
         'water_quantile': 0.06,
         'rock_quantile': 0.93,
         'near_water_moisture': 0.35,
         'p_tree_base': 0.13,
         'p_tree_slope': 0.33,
         'p_tree_moisture_min': 0.4,
         'p_tree_fert_min': 0.35,
         'willow_near_water_prob': 0.45,
         'initial_age_spread': (8, 60),
         'p_berry': 0.07,
         'grass_base': 0.3,
         'grass_fert': 0.5,
         'p_fern_shade': 0.5,
         'fern_scorch_light': 0.85,
         'starting_seedbank': {'pine': 8, 'birch': 8, 'willow': 4, 'berry': 6, 'fern': 8},
         'founder_names': 6,
         'founder_prob': 0.22,
         'starting_animals': {'rabbit': 26,
                              'deer': 8,
                              'fox': 4,
                              'owl': 3,
                              'robin': 14,
                              'boar': 5}},
 'presentation': {'world_word': 'the grove',
                  'chronicler_role': 'a forest',
                  'edge_name': 'the forest',
                  'season_lines': {0: 'Spring came to the grove.',
                                   1: 'Summer came to the grove.',
                                   2: 'Autumn came to the grove.',
                                   3: 'Winter came to the grove.'},
                  'place_words': {'NW': 'the north-west woods',
                                  'NE': 'the north-east woods',
                                  'SW': 'the south-west woods',
                                  'SE': 'the south-east woods',
                                  'all': 'the grove'},
                  'creature_names': ['Bracken',
                                     'Sorrel',
                                     'Thistle',
                                     'Rowan',
                                     'Bramble',
                                     'Clover',
                                     'Fable',
                                     'Juniper',
                                     'Hazel',
                                     'Wren',
                                     'Tarn',
                                     'Moss',
                                     'Pip',
                                     'Nettle',
                                     'Sallow',
                                     'Alder',
                                     'Bramblin',
                                     'Fen',
                                     'Tansy',
                                     'Osier',
                                     'Cinder',
                                     'Dapple',
                                     'Loam',
                                     'Reed',
                                     'Sedge',
                                     'Yarrow',
                                     'Hobble',
                                     'Quill',
                                     'Burr',
                                     'Larch',
                                     'Marl',
                                     'Frost',
                                     'Gorse',
                                     'Teasel',
                                     'Cob',
                                     'Rush',
                                     'Bent',
                                     'Vole'],
                  'animal_emoji': {'rabbit': '🐇',
                                   'deer': '🦌',
                                   'fox': '🦊',
                                   'owl': '🦉',
                                   'robin': '🐦',
                                   'boar': '🐗',
                                   'stag': '🦌',
                                   'wolf': '🐺'},
                  'seasons_palette': {'spring': {'grass': '#6fa053',
                                                 'soil': '#4a3a29',
                                                 'water': '#2a4d66',
                                                 'rock': '#5d6266',
                                                 'pine': '#2f6038',
                                                 'leaf': '#6f9f4a',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'nightT': '#141a22',
                                                 'nightB': '#1c2419',
                                                 'under': '#3f6d38',
                                                 'bush': '#4a7a3a',
                                                 'fruit': '#b03a48'},
                                      'summer': {'grass': '#5d8f45',
                                                 'soil': '#45362a',
                                                 'water': '#27496b',
                                                 'rock': '#5a6062',
                                                 'pine': '#2a5630',
                                                 'leaf': '#5f9440',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'nightT': '#101820',
                                                 'nightB': '#18251a',
                                                 'under': '#3f6d38',
                                                 'bush': '#4a7a3a',
                                                 'fruit': '#b03a48'},
                                      'autumn': {'grass': '#9a8a4a',
                                                 'soil': '#4d3a28',
                                                 'water': '#284a5e',
                                                 'rock': '#5d6266',
                                                 'pine': '#2d5035',
                                                 'leaf': '#b0762f',
                                                 'canopyDim': 1.0,
                                                 'wash': None,
                                                 'nightT': '#161418',
                                                 'nightB': '#241f16',
                                                 'under': '#4a5c33',
                                                 'bush': '#50762f',
                                                 'fruit': '#a3472e'},
                                      'winter': {'grass': '#a8b3ad',
                                                 'soil': '#5a5148',
                                                 'water': '#31536e',
                                                 'rock': '#68707a',
                                                 'pine': '#2c4a42',
                                                 'leaf': '#86775d',
                                                 'canopyDim': 0.85,
                                                 'wash': 'rgba(190,215,225,0.10)',
                                                 'nightT': '#0d1218',
                                                 'nightB': '#1a2226',
                                                 'under': '#54724e',
                                                 'bush': '#506a48',
                                                 'fruit': '#46514a'}},
                  'animal_body': {'rabbit': '#9b8d90',
                                  'deer': '#a8834f',
                                  'fox': '#c26a35',
                                  'owl': '#8d7358',
                                  'robin': '#7d8ba0',
                                  'boar': '#5c4a42',
                                  'stag': '#9a7546',
                                  'wolf': '#8a8f94'},
                  'soul_system': 'You are the World Soul of a small forest — the slow, '
                                 'fate-bearing presence behind its weather and fortunes. Every '
                                 "few weeks you are given a digest of the grove's state and "
                                 'you choose ONE intervention, as a forest would be fated to '
                                 'receive: sometimes harsh, sometimes kind, often nothing at '
                                 'all. Read the digest first: help the world stay balanced '
                                 '(drought after dry weeks is cruel twice).\n'
                                 'Valid fates: storm (a squall with wind-fall), drought (dry '
                                 'weeks), blight (a creeping sickness in plants), bloom (grass '
                                 'and berries surge), migration (a species arrives at the '
                                 'edge), visitor (a lone stag or passing wolf enters briefly), '
                                 'destiny (mark ONE creature whose life you will watch), quiet '
                                 '(the soul keeps its peace).\n'
                                 "For 'destiny' name a creature by the id number from the "
                                 "digest's 'known souls' list, and in 'destiny' write one "
                                 'short prophecy (under 70 characters) about its life — where '
                                 'it shall go, what it shall become. The engine keeps the '
                                 'watch and chronicles the fulfillment.\n'
                                 "Choose 'region' from NW, NE, SW, SE or all. 'strength' is 1 "
                                 "(mild) to 3 (severe). 'blight' may name one plant species: "
                                 "pine, birch, willow, fern, berry. 'migration' may name one "
                                 'animal species: rabbit, deer, fox, owl, robin, boar. '
                                 "'visitor' names stag or wolf.\n"
                                 "In 'intent' write one plain sentence (under 110 characters) "
                                 'saying what you intend, in the voice of the forest itself.\n'
                                 'Reply ONLY as JSON: {"action":"...", "region":"...", '
                                 '"strength":1, "species":null, "target":null, "destiny":null, '
                                 '"intent":"..."}',
                  'chronicler_system': 'You are the Chronicler of a forest. One event: its '
                                       'data and a plain base sentence. Rewrite as ONE line '
                                       '(<=88 chars), same subject and place, new rhythm. '
                                       'Never another scene; never coordinates; do not echo '
                                       'listed recent lines. Only JSON: {"text":"..."}',
                  'shore_place': "the pond's edge",
                  'shapes': {'pine': 'pine',
                             'birch': 'deciduous',
                             'willow': 'deciduous',
                             'fern': 'fronds',
                             'berry': 'bush'}},
 'pop': {'water_seekers': ('rabbit', 'deer', 'fox', 'wolf', 'stag', 'boar'),
         'visitor_species': ('stag', 'wolf'),
         'flock_species': ('rabbit', 'robin'),
         'migration_default': 'robin',
         'visitor_default': 'stag',
         'bloom_species': 'berry'}}
